# Pickle Module

## pickling (dump)

In [6]:

import pickle

dogs_dict = {
    'Ozzy': 3, 
    'Filou': 8, 
    'Luna': 5, 
    'Skippy': 10, 
    'Barco': 12, 
    'Balou': 9, 
    'Laika': 16
}
filename = 'dogs.txt'
outfile = open(filename, 'wb')
pickle.dump(obj=dogs_dict, file=outfile)
outfile.close()


## unpickling (load)

In [7]:

import pickle

infile = open(filename, 'rb')
new_dict = pickle.load(file=infile, encoding='ASCII', errors='strict')
infile.close()
print(new_dict)
print(new_dict == dogs_dict)
print(type(new_dict))


{'Ozzy': 3, 'Filou': 8, 'Luna': 5, 'Skippy': 10, 'Barco': 12, 'Balou': 9, 'Laika': 16}
True
<class 'dict'>


### unpickling objects from Python2 in Python3

In [8]:

import pickle

infile = open(file=filename, mode='rb')
new_dict = pickle.load(file=infile, encoding='latin1', errors='strict')
infile.close()
print(new_dict)


{'Ozzy': 3, 'Filou': 8, 'Luna': 5, 'Skippy': 10, 'Barco': 12, 'Balou': 9, 'Laika': 16}


### unpickling numpy arrays

In [9]:

import numpy as np
import pickle

ones = np.ones(shape=(3, 3), dtype='i8')
print(ones)
filename = 'ones.txt'
outfile = open(filename, mode='wb')
pickle.dump(obj=ones, file=outfile)
outfile.close()

infile = open(file=filename, mode='rb')
new_ones = pickle.load(file=infile, encoding='bytes', errors='strict')
infile.close()
print(new_ones)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Compressing Pickle Files

In [10]:

import bz2
import pickle

sfile = bz2.BZ2File(filename='smallerfile', mode='w', buffering=None, compresslevel=9)
pickle.dump(obj=dogs_dict, file=sfile)
