In [2]:
#Dealing with missing values
import numpy as np
import pandas as pd

ex = np.array(np.arange(0, 20).reshape(2, 2, 5))
print(ex)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
